latlong:
  ip2location:
    format: hex_tsv
    lat_col: 5
    long_col: 6
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ip2location-city/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ip2location-city/ipv6.tsv?inline=false"
  geolite2:
    format: hex_tsv
    lat_col: 6
    long_col: 7
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geolite2-city/ipv4-en.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geolite2-city/ipv6-en.tsv?inline=false"
  dbip:
    format: hex_tsv
    lat_col: 5
    long_col: 6
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/dbip-city/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/dbip-city/ipv6.tsv?inline=false"

country:
  geo-whois-asn-country:
    format: hex_tsv
    asn_col: 3
    org_col: 4
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geo-whois-asn-country/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/geo-whois-asn-country/ipv6.tsv?inline=false"
  ipinfo-country:
    format: hex_tsv
    ipv4: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ipinfo-country/ipv4.tsv?inline=false"
    ipv6: "https://gitlab.com/tdulcet/ip-geolocation-dbs/-/raw/main/ipinfo-country/ipv6.tsv?inline=false"
  iplocate-country:
    # single combined (ipv4+ipv6) CIDR csv
    format: cidr_csv
    ipv4: "https://media.githubusercontent.com/media/iplocate/ip-address-databases/refs/heads/main/ip-to-country/ip-to-country.csv.zip"
    ipv6: "https://media.githubusercontent.com/media/iplocate/ip-address-databases/refs/heads/main/ip-to-country/ip-to-country.csv.zip"
  cn-clang:
    format: cidr_txt
    country: "CN"
    ipv4: "https://ispip.clang.cn/all_cn.txt"
    ipv6: "https://ispip.clang.cn/all_cn_ipv6.txt"
  cn-17mon:
    format: cidr_txt
    country: "CN"
    ipv4: "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"
  cn-chnroutes2:
    format: cidr_txt
    country: "CN"
    ipv4: "https://raw.githubusercontent.com/misakaio/chnroutes2/refs/heads/master/chnroutes.txt"

asn:
  iptoasn:
    format: iptoasn_tsv
    ipv4: "https://iptoasn.com/data/ip2asn-v4-u32.tsv.gz"
    ipv6: "https://iptoasn.com/data/ip2asn-v6.tsv.gz"
